version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:      
      DOCKERHUB_PASSWORD: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker-compose -f docker-compose-build.yaml build
            docker logout
            docker login -u adnananis --password-stdin
            docker-compose -f docker-compose-build.yaml push
