version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.9.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y docker-compose
      - run:
          name: Build and tag Docker images
          command: |
            docker-compose -f docker-compose-build.yaml build
            docker tag my-image:latest adnananis/my-image:latest
            docker tag my-other-image:latest adnananis/my-other-image:latest
      - docker:
          registry: adnananis
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          email: adnananis@hotmail.com
          command: push
          tags:
            - latest
            - my-image:latest
            - my-other-image:latest
