version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:      
      DOCKERHUB_PASSWORD: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml push
