apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagramfrontend
  name: udagramfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
        service: udagramfrontend
  template:
    metadata:
      labels:
        service: udagramfrontend
    spec:
      containers:
      - image: adnananis/udagram-frontend
        name: udagramfrontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always